<a href="https://colab.research.google.com/github/DeV-21/Swabhav_Assignments/blob/main/NumpyAssignment27_06_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Easy Questions -

1. Create a 1D array of 20 sequential integers and reshape it into a 4x5 matrix.


In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(1,21)
print("Array:", arr1)
reshaped_arr1 =  arr1.reshape(4,5)
print(f"\nArray reshaped into 4x5 matrix:")
print(reshaped_arr1)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Array reshaped into 4x5 matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


2. Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

In [ ]:
arr2 = np.arange(22,71,2)
print(f"Even Numbers between 21 and 70: {arr2}")

Even Number between 21 and 70: [22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]


3. Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

In [ ]:
arr3 = np.arange(21,72,2)
print(f"Odd Numbers between 20 and 71: {arr3}")

Odd Numbers between 20 and 71: [21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


4. Generate an array of 15 random integers and sort it in ascending order.

In [ ]:
arr4 = np.random.randint(0,100, size = 15)
print(f"Original Array: {arr4}")

sorted = np.sort(arr4)
print(f"Sorted Array: {sorted}")

Original Array: [51 77 65 44 13 27 48 23 31 67 10 52 32 84 76]
Sorted Array: [10 13 23 27 31 32 44 48 51 52 65 67 76 77 84]


5. Create a 1D array of zeros of length 10 and set the 5th element to 1.

In [ ]:
arr5 = np.zeros(10, dtype = int)
print(f"Original Array: {arr5}")

arr5[4] = 1
print(f"Modified Array: {arr5}")

Original Array: [0 0 0 0 0 0 0 0 0 0]
Modified Array: [0 0 0 0 1 0 0 0 0 0]


6. Find the unique elements in a given array [1, 2, 2, 3, 4, 4, 5].

In [ ]:
arr6  = np.array([1,2,2,3,4,4,5])
print(f"Original Array: {arr6}")
print(f"Unique Elements in the array: {np.unique(arr6)}")

Original Array: [1 2 2 3 4 4 5]
Unique Elements in the array: [1 2 3 4 5]


7. Create an array with values ranging from 0 to 10 and reverse the array.

In [ ]:
arr7 =  np.arange(0,11)
print(f"Original array: {arr7}")

reversed_arr = arr7[::-1]
print(f"Reversed array: {reversed_arr}")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10]
Reversed array: [10  9  8  7  6  5  4  3  2  1  0]


8. Given a list of birds and their corresponding age, calculate:
- a. the mean age of the Crane bird (rounded off to 2 decimal points)
- b. find the name of the oldest bird in the list
  - birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
  - age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [ ]:
birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

birds_arr = np.array(birds)
age_arr = np.array(age)

crane_ages = age_arr[birds_arr == "Cranes"]
mean_crane_age = np.round(crane_ages.mean(), 2)
print(f"Mean age of Crane birds: {mean_crane_age}")

max_index = np.argmax(age_arr)
oldest_bird = birds_arr[max_index]
print(f"Oldest bird in the birds list is: {oldest_bird}")

Mean age of Crane birds: 4.75
Oldest bird in the birds list is: plovers


9. Given a 2d array, write a program to return a subarray such that the subarray consists of the
elements from:
- a. the second to the fourth row of the original array,
- b. the elements in these rows should be from the last three columns of the corresponding rows of the original array,
- c. the rows should be in reversed order.

In [ ]:
import numpy as np
arr2d = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14,15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
print("2d Array:")
print(arr2d)

subarr = arr2d[1:4,-3:][::-1]
print("\nSubarray:")
print(subarr)

2d Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Subarray:
[[18 19 20]
 [13 14 15]
 [ 8  9 10]]


In [ ]:
arr2d = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14,15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
print("2d Array:")
print(arr2d)

subarr = arr2d[1:4,2:][::-1]
print("\nSubarray:")
print(subarr)

2d Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Subarray:
[[18 19 20]
 [13 14 15]
 [ 8  9 10]]


### Moderate Questions -

1. Create a 4x4 matrix and replace all elements on its diagonal with 7.


In [ ]:
mat = np.zeros((4,4), dtype = int)
print("Original Matrix: ")
print(mat)

np.fill_diagonal(mat, 7)
print("\nModified Matrix:")
print(mat)

Original Matrix: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Modified Matrix:
[[7 0 0 0]
 [0 7 0 0]
 [0 0 7 0]
 [0 0 0 7]]


In [ ]:
mat = np.zeros((4, 4), dtype=int)

for i in range(mat.shape[0]):
    for j in range(mat.shape[1]):
        if i == j:
            mat[i, j] = 7

print(mat)

[[7 0 0 0]
 [0 7 0 0]
 [0 0 7 0]
 [0 0 0 7]]


2. Given two arrays of the same size, compute their element-wise product.


In [ ]:
import numpy as np

arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 3, 5])

product = np.multiply(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise product:", product)

Array 1: [2 4 6]
Array 2: [1 3 5]
Element-wise product: [ 2 12 30]


In [ ]:
mat1 = np.random.randint(10, size=(3,3))
print("Matrix a:")
print(mat1)

mat2 = np.random.randint(10, size=(3,3))
print("\nMatrix b: ")
print(mat2)

mat_prod = np.multiply(mat1, mat2)
print("\nElement wise product of matrix a and b:")
print(mat_prod)

Matrix a:
[[5 4 2]
 [0 0 2]
 [2 2 0]]

Matrix b: 
[[3 9 3]
 [9 3 7]
 [2 3 5]]

Element wise product of matrix a and b:
[[15 36  6]
 [ 0  0 14]
 [ 4  6  0]]


3. Create a random 6x6 matrix and compute the mean and standard deviation of its elements.


In [ ]:
mat3 = np.random.randint(100, size = (6,6))
print("Random 6x6 Matrix:")
print(mat3)

print(f"\nMean of the matrix: {np.mean(mat3)}")
print(f"\nStandard Deviation of the matrix: {np.std(mat3)}")

Random 6x6 Matrix:
[[56 22 84 74 88 65]
 [76 79 82 34 10 41]
 [88 20 77 99 48 89]
 [83 18 24 40 61  2]
 [10 61  9 68 46 12]
 [51 14 67 69 47 27]]

Mean of the matrix: 51.138888888888886

Standard Deviation of the matrix: 28.203775139132798


4. Stack two arrays vertically and horizontally (use vstack and hstack).


In [ ]:
arr1 = np.random.randint(0,10, size = 5)
print(f"Array 1: {arr1}")

arr2 = np.random.randint(0,10, size = 5)
print(f"Array 2: {arr2}")

v_result = np.vstack((arr1, arr2))
print(f"\nVertical Stack (vstack):")
print(v_result)

h_result = np.hstack((arr1, arr2))
print(f"\nHorizontal Stack (hstack):")
print(h_result)

Array 1: [4 2 5 4 2]
Array 2: [4 4 4 0 9]

Vertical Stack (vstack):
[[4 2 5 4 2]
 [4 4 4 0 9]]

Horizontal Stack (hstack):
[4 2 5 4 2 4 4 4 0 9]


5. Create a 1D array of 50 random floats between 0 and 1, and count how many values are
greater than 0.5.


In [ ]:
import numpy as np

arr3 = np.random.rand(50)
print("1D array of 50 random floats:")
print(arr3)

# counter = 0
# for a in arr3:
#   if a > 0.5:
#     counter += 1
# print(f"\n{counter} values are greater than 0.5")

count = np.sum(arr3 > 0.5)
print(f"\n{count} values are greater than 0.5")

1D array of 50 random floats:
[0.50364386 0.64621221 0.35649288 0.60854806 0.67904958 0.85104634
 0.29546024 0.77302216 0.77827631 0.97438073 0.98497115 0.42639676
 0.94111568 0.33001468 0.9703033  0.56495404 0.15546606 0.22408959
 0.60678262 0.08894376 0.31840584 0.53785307 0.2136401  0.78093823
 0.86593265 0.5203757  0.48750631 0.50319123 0.13383839 0.34422164
 0.71798765 0.01021527 0.14103571 0.60380268 0.22903173 0.18517493
 0.69869049 0.03860485 0.95053389 0.15721187 0.32000766 0.98345514
 0.09314709 0.782944   0.98520586 0.28290286 0.49201042 0.78703948
 0.81127289 0.60424684]

28 values are greater than 0.5


6. Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)
- birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
- age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]


In [ ]:
birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

birds_arr = np.array(birds)
age_arr = np.array(age)

sorted_indices = np.argsort(age_arr)

sorted_birds = [birds[i] for i in sorted_indices]

print("Birds sorted by age (ascending):")
print(sorted_birds)

Birds sorted by age (ascending):
['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'spoonbills', 'Cranes', 'plovers', 'spoonbills']


7. Given the shape of an array and a range, Return an array of specified shape, consisting of random integers from "discrete uniform" distribution, in given range [low, high].
* Note: high is inclusive in range.
- Input Format:
  - Input has two lines.
  - First line contains the shape of the array.
  - Second line contains the range (low, high).
- Output Format: A NumPy array


In [ ]:
shape = tuple(map(int, input("Enter shape (space-separated): ").split()))
low, high = map(int, input("Enter low and high values: ").split())

arr = np.random.randint(low, high + 1, size=shape)

print("\nGenerated array:")
print(arr)

Enter shape (space-separated): 2 3
Enter low and high values: 10 20

Generated array:
[[13 12 18]
 [17 12 20]]


### Challenging Questions -

1. Create a 10x10 matrix with random integers and find the indices of the top 3 maximum
values.
  - Concepts: Matrix generation, indexing with conditions.


In [ ]:
mat = np.random.randint(1,101, size = (10,10))
print("10x10 matrix with random integers:")
print(mat)

flat = mat.flatten()
sorted_indices = np.argsort(flat)[::-1]
top3_flat_indices = sorted_indices[:3]
top3_indices = np.unravel_index(top3_flat_indices, mat.shape)
top3_positions = list(zip(top3_indices[0], top3_indices[1]))
print("\nIndices of top 3 maximum values:")
print(top3_positions)

rows, cols = np.unravel_index(top3_flat_indices, mat.shape)
clean_indices = [(int(r), int(c)) for r, c in zip(rows, cols)]

print("Top 3 indices (clean):")
print(clean_indices)

10x10 matrix with random integers:
[[ 69  10   3  94   1  85  12   9  82  92]
 [ 23  37   6  85  25   3  43  46  56  71]
 [ 87  23  94 100  22  89  54  16  64  94]
 [ 64   3  44   2  40  96  89  42  24  86]
 [ 49   7  82  21   8  70  66  59  45  61]
 [ 15  63  34  75  85  87  68  29  83  90]
 [ 94  96  90  98  13  94  94  25  30  11]
 [ 23  77  55   8  27  62   9  33  30   5]
 [ 42  38   5  26  44  54  86  60  44  27]
 [ 63  38  80  49  26  22   7  95  58   6]]

Indices of top 3 maximum values:
[(np.int64(2), np.int64(3)), (np.int64(6), np.int64(3)), (np.int64(6), np.int64(1))]
Top 3 indices (clean):
[(2, 3), (6, 3), (6, 1)]


2. Solve a system of three linear equations using NumPy’s linalg.solve() function.
  - Concepts: Linear algebra, system of equations.

In [ ]:
A = np.array([[[2, 1, -1],
               [-3, -1, 2],
               [-2, 1, 2]]])

B = np.array([8, -11, -3])

X = np.linalg.solve(A, B)

print("Solution for x, y, z:")
print((X))

print("\nVerification (A @ X):")
print(A @ X.flatten())

Solution for x, y, z:
[[ 2.  3. -1.]]

Verification (A @ X):
[[  8. -11.  -3.]]


3. Generate a random 8x8 matrix and compute its eigenvalues and eigenvectors.
  - Concepts: Linear algebra, eigenvalues/eigenvectors.

In [ ]:
A = np.random.rand(8, 8)
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 3.70247955+0.j          0.85176625+0.j          0.18333315+0.74391949j
  0.18333315-0.74391949j -0.91520294+0.j         -0.48462354+0.j
 -0.08155073+0.18717814j -0.08155073-0.18717814j]

Eigenvectors:
[[-0.35446074+0.j         -0.60949605+0.j          0.54063144+0.j
   0.54063144-0.j          0.17351694+0.j         -0.02523406+0.j
   0.15752124+0.16803589j  0.15752124-0.16803589j]
 [-0.34056552+0.j          0.59015499+0.j          0.03246737-0.19432893j
   0.03246737+0.19432893j -0.40102681+0.j         -0.57988105+0.j
  -0.1711991 +0.09260427j -0.1711991 -0.09260427j]
 [-0.16188076+0.j         -0.09311682+0.j         -0.20773856+0.24813206j
  -0.20773856-0.24813206j -0.10546138+0.j         -0.37082448+0.j
  -0.69630459+0.j         -0.69630459-0.j        ]
 [-0.39474593+0.j         -0.10521969+0.j         -0.19722543-0.18208095j
  -0.19722543+0.18208095j -0.18871263+0.j          0.51529347+0.j
   0.4372814 +0.07971677j  0.4372814 -0.07971677j]
 [-0.4335617 +0.j          0

4. Create a large random matrix (1000x1000) and find the time taken to compute the sum
of its elements.
  - Concepts: Performance evaluation, time computation.


In [ ]:
import numpy as np
import time

mat = np.random.rand(1000, 1000)

start = time.time()

total_sum = np.sum(mat)

end = time.time()

print("Sum of all elements:", total_sum)
print("Time taken (seconds):", end - start)

Sum of all elements: 500089.69538929925
Time taken (seconds): 0.0007815361022949219


In [ ]:
mat2 = np.random.randint(1,1000, size = (1000,1000))
%timeit np.sum(mat2)

394 µs ± 84.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


5. Implement matrix multiplication of two large matrices (500x500) without using
numpy.dot() and compare the performance with NumPy's dot product.
  - Concepts: Matrix multiplication, performance comparison.

In [ ]:
A = np.random.rand(500, 500)
B = np.random.rand(500, 500)

start = time.time()
C_manual = np.zeros((500, 500))

for i in range(500):
    for j in range(500):
        for k in range(500):
            C_manual[i, j] += A[i, k] * B[k, j]

end = time.time()
print("Time taken (manual loops):", end - start)

start = time.time()
C_numpy = np.dot(A, B)
end = time.time()
print("Time taken (NumPy dot):", end - start)

Time taken (manual loops): 81.74833822250366
Time taken (NumPy dot): 0.025294065475463867


In [ ]:
A

array([[0.01782432, 0.66143314, 0.20833444, ..., 0.61260832, 0.85807109,
        0.89039094],
       [0.95956549, 0.08076704, 0.42132728, ..., 0.52486833, 0.26936497,
        0.79975411],
       [0.95684118, 0.85524614, 0.76622777, ..., 0.10412504, 0.08374074,
        0.11588302],
       ...,
       [0.91401383, 0.55164117, 0.39824734, ..., 0.08734108, 0.35172946,
        0.87620574],
       [0.85112485, 0.50161843, 0.43175835, ..., 0.51430209, 0.56898189,
        0.24962071],
       [0.61925142, 0.66590871, 0.32765169, ..., 0.16348165, 0.13146945,
        0.74742701]])

In [ ]:
B

array([[0.23832545, 0.33413312, 0.39696751, ..., 0.16077434, 0.89761361,
        0.19789172],
       [0.7634787 , 0.70549928, 0.10980468, ..., 0.8077137 , 0.95356415,
        0.71931136],
       [0.82967947, 0.77503311, 0.82028383, ..., 0.12950167, 0.26104366,
        0.65959257],
       ...,
       [0.8293558 , 0.41382486, 0.03435911, ..., 0.40607168, 0.89837881,
        0.92862142],
       [0.67239737, 0.43008004, 0.95174271, ..., 0.34623397, 0.92232035,
        0.05994934],
       [0.06418565, 0.37502726, 0.42558589, ..., 0.20188509, 0.96363393,
        0.92351307]])